import 'antd/dist/reset.css';
import './global.scss';
import { ThemeProvider } from '@/components/Theme/ThemeProvider';
import { Toolbar } from '@/components/Toolbar/Toolbar';
import ReduxProvider from '../store/ReduxProvider';
import styles from './Layout.module.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProvider>
            <Toolbar />
            <div className={styles.centered}>{children}</div>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
